### PR TITLE
Annotation field

### PR DESCRIPTION
**Pull request by mahyar-osn**
Adding a new _stored string field_ to the generated EX file when the XML has a 'type' (e.g. Axon or Dendrite) in its <tree>.

### CODE REVIEW

**Review by hsorby — COMMENTED** [review]
You need to add at least two tests showing:

1. that the package can handle the 'property' tag
2. that the package writes out the 'annotation' file into an ex file
 
(which should have been done before the implementation.)

**Comment by hsorby** [comment]
You need to add some tests for this new code.

**Review by hsorby — CHANGES_REQUESTED** [review]
Can you add a test to check that the annotation you are expecting appears in an output file.

**Comment by hsorby** [comment]
We will need to change this annotation extraction because it would be better to have it put into a separate file that makes statements about the group.  But we will leave that for after this PR.  One thing that this will mean is that this information will not be available from the ex file in the near future.

**Comment by mahyar-osn** [comment]
Just made the changes as requested. Additionally, I agree with having a separate file for annotation groups.

**Review by hsorby — APPROVED** [review]

**Pull request merged**
